### ISSUE TITLE
Can't find Supplemental Data Zip File

### ISSUE THREAD

**Issue by steve273** [tgen/banovichlab#2]
Hello, the supplement suggests seeing a zip file for a number of the supplemental tables but I cannot see the link to the zip file online at the journal here: https://www.science.org/doi/10.1126/sciadv.aba1972

Could you make this more prominent?

**Comment by lo2811** [comment]
Hello,

Thank you for pointing out this missing information in our paper. We are sorry for the inconvenience and are looking into this issue. We'll contact the editor and get back to you as soon as possible.

Linh

**Comment by lo2811** [comment]
Hello Steve,
We have contacted the editor regarding the missing files, the files were included in our final submission but unfortunately missing in the publication. Please send me an email at lbui@tgen.org if you need the files immediately and I'll send them to you. Thank you.

Linh
